#!/bin/bash -e

# script/test: Run test suites for application.

if [ "$RUBY_ENV" = "test" ]; then
	# if executed and the environment is already set to `test`, then we want a
	# clean from scratch application. This almost always means a ci environment,
	# since we set the environment to `test` directly in `script/cibuild`.
	script/bootstrap
	export CI_REPORTS="test/reports/unit"
else
	# if the environment isn't set to `test`, set it to `test` and update the
	# application to ensure all dependencies are met as well as any other things
	# that need to be up to date, like db migrations. The environment not having
	# already been set to `test` almost always means this is being called on it's
	# own from a `development` environment.
	script/bootstrap
	export RUBY_ENV='test'
fi

echo "=> Run unit tests"
rake test:unit
echo "=> Done"
